# Generated by Django 3.2.7 on 2021-10-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateUAH', models.CharField(max_length=9)),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
